# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceBullet.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_ImportFile(object):
    def setupUi(self, ImportFile):
        ImportFile.setObjectName("ImportFile")
        ImportFile.resize(423, 492)
        self.centralwidget = QtWidgets.QWidget(ImportFile)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -10, 441, 521))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(35, 35, 35, 255), stop:1 rgba(46, 46, 46, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.importButton = QtWidgets.QPushButton(self.frame)
        self.importButton.setGeometry(QtCore.QRect(330, 460, 81, 31))
        self.importButton.setStyleSheet("font: 9pt \"Poppins\";\n"
"color: rgb(255, 255, 255);")
        self.importButton.setObjectName("importButton")
        self.cancelButton = QtWidgets.QPushButton(self.frame)
        self.cancelButton.setGeometry(QtCore.QRect(240, 460, 81, 31))
        self.cancelButton.setStyleSheet("font: 9pt \"Poppins\";\n"
"color: rgb(255, 255, 255);")
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.label.setStyleSheet("font: 9pt \"Poppins\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: transparent;")
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 50, 401, 401))
        self.plainTextEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        ImportFile.setCentralWidget(self.centralwidget)

        self.retranslateUi(ImportFile)
        QtCore.QMetaObject.connectSlotsByName(ImportFile)

        self.cancelButton.clicked.connect(ImportFile.close)
        self.importButton.clicked.connect(self.saveFile)

    def retranslateUi(self, ImportFile):
        _translate = QtCore.QCoreApplication.translate
        ImportFile.setWindowTitle(_translate("ImportFile", "MainWindow"))
        self.importButton.setText(_translate("ImportFile", "Import"))
        self.cancelButton.setText(_translate("ImportFile", "Cancel"))
        self.label.setText(_translate("ImportFile", "Import File"))

#     def saveFile(self): # this function require to choose the folder
#         text = self.plainTextEdit.toPlainText()
#         file_path, _ = QtWidgets.QFileDialog.getSaveFileName(
#             None, "Save File", "", "Text Files (*.txt)"
#         )
#         if file_path:
#             with open(file_path, "w") as file:
#                 file.write(text)

    def saveFile(self):
        text = self.plainTextEdit.toPlainText()
        file_path = "storage/acc.txt"

        try:
            if os.path.exists(file_path):
                with open(file_path, "a") as file:
                    file.write("\n" + text)
            else:
                # Create the directory if it doesn't exist
                directory = os.path.dirname(file_path)
                os.makedirs(directory, exist_ok=True)

                with open(file_path, "w") as file:
                    file.write(text)

            QtWidgets.QMessageBox.information(
                None, "File Saved", f"The file has been saved to {file_path}."
            )

        except Exception as e:
            QtWidgets.QMessageBox.critical(
                None, "Error", f"An error occurred while saving the file:\n{str(e)}"
            )


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImportFile = QtWidgets.QMainWindow()
    ui = Ui_ImportFile()
    ui.setupUi(ImportFile)
    ImportFile.show()
    sys.exit(app.exec_())
